In [1]:
# ---*--*--*--*--*--*--*--*--*--- Run Visualization ---*--*--*--*--*--*--*--*--*---
from pathlib import Path
from shantay.viz import visualize

# Update for your environment
PATH = "/Volumes/dsa-sor-db/data"

visualize(Path(PATH), Path.cwd() / "dsa-db-staging")

| Attribute                                     | Value                                         |
| :-------------------------------------------- | :-------------------------------------------- |
| Dates                                         | 2023-09-25 to 2025-03-02 (inclusive)          |
| Platforms reporting Protection of Minors SoRs | 11 out of 44 include keywords, 8 include CSAM |
| Protection of Minors SoRs                     | 59.3 megarows out of 27.2 gigarows or 0.2%    |
| Protection of Minors SoRs with keywords       | 9.9% of category vs 3.4% of all SoRs          |
| Size of in-memory frames                      | 49.3 gigabyte                                 |

| variable                                   |          value  |
| ------------------------------------------ | -------------: |
| total_rows                                 | 27,103,404,236 |
| total_rows_with_keywords                   |    493,395,977 |
| ⠀                                          |              ⠀ |
| batch_count                                |         34,232 |
| ⠀                                          |              ⠀ |
| rows                                       |     58,868,237 |
| keywords                                   |      5,609,725 |
| rows_with_keywords                         |      5,609,706 |
| max_keywords_per_row                       |              3 |
| ⠀                                          |              ⠀ |
| illegal_content                            |        180,756 |
| incompatible_content                       |     58,687,481 |
| ⠀                                          |              ⠀ |
| account_suspended_no_date                  |        557,756 |
| account_suspended_until_date               |          4,035 |
| account_suspended_until_date_pct_suspended |          0.718 |
| account_terminated_no_date                 |      3,158,318 |
| account_terminated_until_date              |              0 |
| ⠀                                          |              ⠀ |
| csam                                       |      3,135,143 |
| csam_pct_rows                              |          5.326 |
| ⠀                                          |              ⠀ |
| csam_no_decision                           |              0 |
| csam_visibility_decision_only              |        177,548 |
| csam_monetary_decision_only                |              0 |
| csam_provision_decision_only               |      2,346,130 |
| csam_account_decision_only                 |        475,306 |
| csam_visibility_provision_decision         |              0 |
| csam_visibility_account_decision           |              1 |
| csam_provision_account_decision            |              0 |
| csam_visibility_provision_account_decision |        136,158 |
| ⠀                                          |              ⠀ |
| csam_max_visibility_per_row                |              1 |
| csam_visibility_values                     |        313,707 |
| csam_rows_with_visibility                  |        313,707 |
| csam_no_visibility_decision                |      2,821,436 |
| ⠀                                          |              ⠀ |
| csam_removed                               |        174,406 |
| csam_disabled                              |          3,134 |
| csam_demoted                               |              0 |
| csam_age_restricted                        |              0 |
| csam_interaction_restricted                |              0 |
| csam_labeled                               |              0 |
| csam_other_visibility                      |        136,167 |
| ⠀                                          |              ⠀ |
| csam_monetary_suspension                   |              0 |
| csam_monetary_termination                  |              0 |
| csam_monetary_other                        |              0 |
| csam_no_monetary_decision                  |      3,135,143 |
| ⠀                                          |              ⠀ |
| csam_provision_partial_suspension          |      2,346,130 |
| csam_provision_total_suspension            |        136,152 |
| csam_provision_partial_termination         |              0 |
| csam_provision_total_termination           |              6 |
| csam_no_provision_decision                 |        652,855 |
| ⠀                                          |              ⠀ |
| csam_account_suspended                     |        369,405 |
| csam_account_terminated                    |        242,060 |
| csam_no_account_decision                   |      2,523,678 |
| ⠀                                          |              ⠀ |
| csam_account_suspended_no_date             |        369,405 |
| csam_account_suspended_until_date          |              0 |
| csam_account_terminated_no_date            |        242,060 |
| csam_account_terminated_until_date         |              0 |
| ⠀                                          |              ⠀ |
| csam_illegal_content                       |        136,167 |
| csam_incompatible_content                  |      2,998,976 |
| csam_no_decision_ground                    |              0 |

__Source Data__:

| Column                           | Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| :------------------------------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| uuid                             | String                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| decision_visibility              | List(Enum(categories=['DECISION_VISIBILITY_CONTENT_REMOVED', 'DECISION_VISIBILITY_CONTENT_DISABLED', 'DECISION_VISIBILITY_CONTENT_DEMOTED', 'DECISION_VISIBILITY_CONTENT_AGE_RESTRICTED', 'DECISION_VISIBILITY_CONTENT_INTERACTION_RESTRICTED', 'DECISION_VISIBILITY_CONTENT_LABELLED', 'DECISION_VISIBILITY_OTHER']))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| decision_visibility_other        | String                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| end_date_visibility_restriction  | Datetime(time_unit='ms', time_zone=None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| decision_monetary                | Enum(categories=['DECISION_MONETARY_SUSPENSION', 'DECISION_MONETARY_TERMINATION', 'DECISION_MONETARY_OTHER'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

__meta.json__:

| Column                   | Type   |
| :----------------------- | :----- |
| start_date               | Date   |
| end_date                 | Date   |
| batch_count              | Int64  |
| total_rows               | UInt64 |
| total_rows_with_keywords | UInt64 |
| batch_rows               | UInt64 |
| batch_rows_with_keywords | UInt64 |
| batch_memory             | UInt64 |
| sha256                   | String |

__meta-statistics.parquet__:

| Column                                     | Type   |
| :----------------------------------------- | :----- |
| start_date                                 | Date   |
| end_date                                   | Date   |
| total_rows                                 | UInt64 |
| total_rows_with_keywords                   | UInt64 |
| batch_count                                | UInt64 |
| rows                                       | UInt64 |
| keywords                                   | UInt64 |
| rows_with_keywords                         | UInt64 |
| max_keywords_per_row                       | UInt32 |
| illegal_content                            | UInt64 |
| incompatible_content                       | UInt64 |
| account_suspended_no_date                  | UInt64 |
| account_suspended_until_date               | UInt64 |
| account_terminated_no_date                 | UInt64 |
| account_terminated_until_date              | UInt64 |
| csam                                       | UInt32 |
| csam_no_decision                           | UInt32 |
| csam_visibility_decision_only              | UInt32 |
| csam_monetary_decision_only                | UInt32 |
| csam_provision_decision_only               | UInt32 |
| csam_account_decision_only                 | UInt32 |
| csam_visibility_provision_decision         | UInt32 |
| csam_visibility_account_decision           | UInt32 |
| csam_provision_account_decision            | UInt32 |
| csam_visibility_provision_account_decision | UInt32 |
| csam_max_visibility_per_row                | UInt32 |
| csam_visibility_values                     | UInt32 |
| csam_rows_with_visibility                  | UInt32 |
| csam_no_visibility_decision                | UInt32 |
| csam_removed                               | UInt32 |
| csam_disabled                              | UInt32 |
| csam_demoted                               | UInt32 |
| csam_age_restricted                        | UInt32 |
| csam_interaction_restricted                | UInt32 |
| csam_labeled                               | UInt32 |
| csam_other_visibility                      | UInt32 |
| csam_monetary_suspension                   | UInt32 |
| csam_monetary_termination                  | UInt32 |
| csam_monetary_other                        | UInt32 |
| csam_no_monetary_decision                  | UInt32 |
| csam_provision_partial_suspension          | UInt32 |
| csam_provision_total_suspension            | UInt32 |
| csam_provision_partial_termination         | UInt32 |
| csam_provision_total_termination           | UInt32 |
| csam_no_provision_decision                 | UInt32 |
| csam_account_suspended                     | UInt32 |
| csam_account_suspended_no_date             | UInt32 |
| csam_account_suspended_until_date          | UInt32 |
| csam_account_terminated                    | UInt32 |
| csam_account_terminated_no_date            | UInt32 |
| csam_account_terminated_until_date         | UInt32 |
| csam_no_account_decision                   | UInt32 |
| csam_illegal_content                       | UInt32 |
| csam_incompatible_content                  | UInt32 |
| csam_no_decision_ground                    | UInt32 |

__meta-keywords.parquet__:

| Column     | Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| :--------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| start_date | Date                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| end_date   | Date                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| keyword    | Enum(categories=['KEYWORD_ANIMAL_HARM', 'KEYWORD_UNLAWFUL_SALE_ANIMALS', 'KEYWORD_HIDDEN_ADVERTISEMENT', 'KEYWORD_INSUFFICIENT_INFORMATION_ON_TRADERS', 'KEYWORD_MISLEADING_INFO_CONSUMER_RIGHTS', 'KEYWORD_MISLEADING_INFO_GOODS_SERVICES', 'KEYWORD_NONCOMPLIANCE_PRICING', 'KEYWORD_CYBER_BULLYING_INTIMIDATION', 'KEYWORD_CYBER_HARASSMENT', 'KEYWORD_CYBER_INCITEMENT', 'KEYWORD_CYBER_STALKING', 'KEYWORD_NON_CONSENSUAL_IMAGE_SHARING', 'KEYWORD_NON_CONSENSUAL_MATERIAL_DEEPFAKE', 'KEYWORD_BULLYING_AGAINST_GIRLS', 'KEYWORD_CYBER_HARASSMENT_AGAINST_WOMEN', 'KEYWORD_CYBER_STALKING_AGAINST_WOMEN', 'KEYWORD_FEMALE_GENDERED_DISINFORMATION', 'KEYWORD_INCITEMENT_AGAINST_WOMEN', 'KEYWORD_NON_CONSENSUAL_IMAGE_SHARING_AGAINST_WOMEN', 'KEYWORD_NON_CONSENSUAL_MATERIAL_DEEPFAKE_AGAINST_WOMEN', 'KEYWORD_BIOMETRIC_DATA_BREACH', 'KEYWORD_MISSING_PROCESSING_GROUND', 'KEYWORD_RIGHT_TO_BE_FORGOTTEN', 'KEYWORD_DATA_FALSIFICATION', 'KEYWORD_DEFAMATION', 'KEYWORD_DISCRIMINATION', 'KEYWORD_HATE_SPEECH', 'KEYWORD_COPYRIGHT_INFRINGEMENT', 'KEYWORD_DESIGN_INFRINGEMENT', 'KEYWORD_GEOGRAPHIC_INDICATIONS_INFRINGEMENT', 'KEYWORD_PATENT_INFRINGEMENT', 'KEYWORD_TRADE_SECRET_INFRINGEMENT', 'KEYWORD_TRADEMARK_INFRINGEMENT', 'KEYWORD_DISINFORMATION', 'KEYWORD_MISINFORMATION', 'KEYWORD_MISINFORMATION_DISINFORMATION', 'KEYWORD_VIOLATION_EU_LAW', 'KEYWORD_VIOLATION_NATIONAL_LAW', 'KEYWORD_FOREIGN_INFORMATION_MANIPULATION', 'KEYWORD_NON_CONSENSUAL_ITEMS_DEEPFAKE', 'KEYWORD_ONLINE_BULLYING_INTIMIDATION', 'KEYWORD_STALKING', 'KEYWORD_ADULT_SEXUAL_MATERIAL', 'KEYWORD_IMAGE_BASED_SEXUAL_ABUSE', 'KEYWORD_AGE_SPECIFIC_RESTRICTIONS_MINORS', 'KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL', 'KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL_DEEPFAKE', 'KEYWORD_GROOMING_SEXUAL_ENTICEMENT_MINORS', 'KEYWORD_UNSAFE_CHALLENGES', 'KEYWORD_ILLEGAL_ORGANIZATIONS', 'KEYWORD_RISK_ENVIRONMENTAL_DAMAGE', 'KEYWORD_RISK_PUBLIC_HEALTH', 'KEYWORD_TERRORIST_CONTENT', 'KEYWORD_INAUTHENTIC_ACCOUNTS', 'KEYWORD_INAUTHENTIC_LISTINGS', 'KEYWORD_INAUTHENTIC_USER_REVIEWS', 'KEYWORD_IMPERSONATION_ACCOUNT_HIJACKING', 'KEYWORD_PHISHING', 'KEYWORD_PYRAMID_SCHEMES', 'KEYWORD_CONTENT_PROMOTING_EATING_DISORDERS', 'KEYWORD_SELF_MUTILATION', 'KEYWORD_SUICIDE', 'KEYWORD_AGE_SPECIFIC_RESTRICTIONS', 'KEYWORD_GEOGRAPHICAL_REQUIREMENTS', 'KEYWORD_GOODS_SERVICES_NOT_PERMITTED', 'KEYWORD_LANGUAGE_REQUIREMENTS', 'KEYWORD_NUDITY', 'KEYWORD_INSUFFICIENT_INFORMATION_TRADERS', 'KEYWORD_PROHIBITED_PRODUCTS', 'KEYWORD_UNSAFE_PRODUCTS', 'KEYWORD_REGULATED_GOODS_SERVICES', 'KEYWORD_DANGEROUS_TOYS', 'KEYWORD_COORDINATED_HARM', 'KEYWORD_GENDER_BASED_VIOLENCE', 'KEYWORD_HUMAN_EXPLOITATION', 'KEYWORD_HUMAN_TRAFFICKING', 'KEYWORD_INCITEMENT_VIOLENCE_HATRED', 'KEYWORD_TRAFFICKING_WOMEN_GIRLS', 'KEYWORD_OTHER']) |
| count      | UInt32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

__meta-platforms.parquet__:

| Column      | Type   |
| :---------- | :----- |
| start_date  | Date   |
| end_date    | Date   |
| platform    | String |
| total       | UInt32 |
| has_keyword | UInt32 |
| is_csam     | UInt32 |

shape: (10, 3)
┌───────────────────────────────────────────┬───────────┬────────┐
│ keyword                                   ┆ count     ┆ pct    │
│ ---                                       ┆ ---       ┆ ---    │
│ enum                                      ┆ u32       ┆ f64    │
╞═══════════════════════════════════════════╪═══════════╪════════╡
│ KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL       ┆ 3,135,143 ┆ 55.888 │
│ KEYWORD_OTHER                             ┆ 1,854,134 ┆ 33.052 │
│ KEYWORD_AGE_SPECIFIC_RESTRICTIONS_MINORS  ┆ 544,969   ┆ 9.715  │
│ KEYWORD_GROOMING_SEXUAL_ENTICEMENT_MINORS ┆ 72,325    ┆ 1.289  │
│ KEYWORD_NUDITY                            ┆ 1,633     ┆ 0.029  │
│ KEYWORD_ONLINE_BULLYING_INTIMIDATION      ┆ 1,439     ┆ 0.026  │
│ KEYWORD_HATE_SPEECH                       ┆ 47        ┆ 0.001  │
│ KEYWORD_ADULT_SEXUAL_MATERIAL             ┆ 17        ┆ 0.000  │
│ KEYWORD_HUMAN_TRAFFICKING                 ┆ 16        ┆ 0.000  │
│ KEYWORD_REGULATED_GOODS_SERVICES          ┆ 2         ┆ 0.000  │
└───────────────────────────────────────────┴───────────┴────────┘

alt.Chart(...)

shape: (44, 2)
┌───────┬─────────────────────────────────────────┐
│ index ┆ platform                                │
│ ---   ┆ ---                                     │
│ u32   ┆ str                                     │
╞═══════╪═════════════════════════════════════════╡
│ 0     ┆ AliExpress                              │
│ 1     ┆ Badoo                                   │
│ 2     ┆ Booking.com                             │
│ 3     ┆ Bumble                                  │
│ 4     ┆ Campfire                                │
│ 5     ┆ Canva                                   │
│ 6     ┆ Chrome Web Store                        │
│ 7     ┆ Dailymotion                             │
│ 8     ┆ Discord Netherlands B.V.                │
│ 9     ┆ Facebook                                │
│ 10    ┆ Google Maps                             │
│ 11    ┆ Google Play                             │
│ 12    ┆ Google Shopping                         │
│ 13    ┆ Habbo                                   │
│ 14    ┆ Hinge                                   │
│ 15    ┆ Hotel Hideaway                          │
│ 16    ┆ Idealo                                  │
│ 17    ┆ Instagram                               │
│ 18    ┆ Kleinanzeigen                           │
│ 19    ┆ Meetic SAS                              │
│ 20    ┆ OTTO Market                             │
│ 21    ┆ Pinterest                               │
│ 22    ┆ Pornhub                                 │
│ 23    ┆ Quora Ireland Limited                   │
│ 24    ┆ Rajče                                   │
│ 25    ┆ Reddit                                  │
│ 26    ┆ Roblox                                  │
│ 27    ┆ Snapchat                                │
│ 28    ┆ Stripchat                               │
│ 29    ┆ Temu                                    │
│ 30    ┆ Threads                                 │
│ 31    ┆ TikTok                                  │
│ 32    ┆ Tinder                                  │
│ 33    ┆ VSCO                                    │
│ 34    ┆ Vinted UAB                              │
│ 35    ┆ Wallapop                                │
│ 36    ┆ WhatsApp Channels                       │
│ 37    ┆ X                                       │
│ 38    ┆ YouTube                                 │
│ 39    ┆ Zalando                                 │
│ 40    ┆ bolha.com                               │
│ 41    ┆ leboncoin                               │
│ 42    ┆ willhaben internet service GmbH & Co KG │
│ 43    ┆ www.gutefrage.net                       │
└───────┴─────────────────────────────────────────┘

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.LayerChart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)